---
- name: CICS CMCI Report

  hosts: "localhost"
  gather_facts: false

  vars_prompt:
    - name: cmci_host
      prompt: Target CMCI hostname
      private: false
    - name: cmci_port
      prompt: Target CMCI port
      private: false
    - name: scheme
      prompt: CMCI scheme
      private: false
      default: "https"
    - name: context
      prompt: Target CPSM context
      private: false
    - name: cmci_user
      prompt: CMCI user name (leave blank for unauthenticated)
      private: false
    - name: cmci_password
      prompt: CMCI password (leave blank for unauthenticated)

  vars:
    attributes:
      - eyu_cicsname
      - release
      - jobid
      - totaltasks

  tasks:
    ############################################################################
    # Install module dependencies
    ############################################################################
    - name: Make sure CMCI module dependencies are installed
      ansible.builtin.pip:
        name:
          - requests
          - xmltodict
          - typing;python_version<"3.5"

    ############################################################################
    # Get information about CICS regions from the supplied context, using CMCI
    ############################################################################
    - name: Get information about CICS regions
      ibm.ibm_zos_cics.cmci_get:
        context: "{{ context }}"
        cmci_host: "{{ cmci_host }}"
        cmci_port: "{{ cmci_port | int }}"
        cmci_user: "{{ cmci_user | default(omit) }}"
        cmci_password: "{{ cmci_password | default(omit) }}"
        scheme: "{{ scheme }}"
        type: "CICSRegion"
      register: result

    ############################################################################
    # Print the response from CMCI to the log - useful to see attribute names!
    ############################################################################
    - debug:
        msg: '{{ result }}'

    ############################################################################
    # Write the report csv file using a template
    ############################################################################
    - name: Create CSV report from template
      ansible.builtin.template:
        src: csv.j2
        dest: report.csv
        mode: u+rw

# Run with ansible-playbook -i /Users/andrewhughes/gseuk23/inventory.yml -e @/Users/andrewhughes/gseuk23/vars.yml ./cmci_report.yml