# (c) Copyright IBM Corp. 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Sample zos_job_submit template playbook.
  hosts: zos_host
  gather_facts: false
  environment: '{{ environment_vars }}'

  vars:
    sh_cmd: "uptime"

    sh_program_name: "UPTIME"
    accounting_info: "T043JM,JM00,1,0,0,0"
    programmer: "HUGHEA"
    job_class: "A"
    msg_class: "X"
    msg_stmt_level: 1
    msg_exc_level: 1
    job_notify: "&SYSUID"


  tasks:
    # For the first example, we'll use JCL that executes a shell
    # command in the managed node. The template primarily enables dynamically
    # filling out the job card.
    - name: Submit shell command job using a local template.
      ibm.ibm_zos_core.zos_job_submit:
        src: "{{ playbook_dir }}/job.j2"
        location: LOCAL
        use_template: true
      register: job_output

    - name: Extracting ddnames from job output.
      set_fact:
        job_ddnames: "{{ job_output.jobs[0].ddnames }}"

    # By looking at the submitted JCL, we'll see how Jinja rendered
    # the template without introducing additional whitespace that
    # could cause syntax problems.
    - name: See job's submitted JCL.
      ansible.builtin.debug:
        msg: "{{ job_ddnames | selectattr('ddname', 'equalto', 'JESJCL') }}"

    - name: See job output.
      ansible.builtin.debug:
        msg: "{{ job_ddnames | selectattr('ddname', 'equalto', 'STDOUT') }}"


#ansible-playbook -i /Users/andrewhughes/gseuk23/inventory.yml -e @/Users/andrewhughes/gseuk23/vars.yml ./job_submit.yml